name: Cleanup Old Data

on:
  schedule:
    # Runs at 02:00 UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Clean old data
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NODE_ENV: production
        run: |
          node -e "
          (async () => {
            const { connectDatabase } = await import('./src/config/database.js');
            await connectDatabase();
            const { cleanupService } = await import('./src/services/cleanupService.js');
            await cleanupService.cleanOldData();
            process.exit(0);
          })().catch(err => {
            console.error('Fatal error:', err);
            process.exit(1);
          });
          "